version: '3.8'
services:
  database:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: 
      MONGO_DBNAME: nest
    networks:
      - nestapi
networks:
  nestapi: