version: '3.8'
services:
  dev-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_USER: mehdi
      MONGO_PASSWORD: mehdi123
      MONGO_DBNAME: nest
    networks:
      - nestapi
networks:
  nestapi: