version: '3.8'
services:
  server:
    image: nest-api:1.0.0
    container_name: nestapi_server
    ports:
      - 3000:3000
    networks:
      - nestapi
    depends_on:
      - db
  db:
    image: mongo
    container_name: nestapi_db
    ports:
      - 27017:27017
    networks:
      - nestapi
networks:
  nestapi:
    driver: bridge